#!/usr/bin/env bash
# Regenerates docs/REPO_MAP.md: a directory tree of the repo (ignoring build output,
# git internals, and the SQLite db) so an AI assistant or a new teammate can orient
# without crawling the tree. Run from anywhere; writes relative to the repo root.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/docs/REPO_MAP.md"
cd "$ROOT"

{
  echo "# Repository map"
  echo
  echo "Auto-generated by \`scripts/repo-map.sh\` on $(date '+%Y-%m-%d'). Do not edit by hand."
  echo
  echo '```'
  # Prefer `tree` if installed; fall back to a find-based tree.
  if command -v tree >/dev/null 2>&1; then
    tree -a -I '.git|target|node_modules|*.db|*.class|.DS_Store|.idea|*.iml' --dirsfirst --noreport .
  else
    find . \( -path ./.git -o -path '*/target' -o -name '*.db' -o -name '.DS_Store' -o -path '*/.idea' \) -prune -o -print \
      | sort \
      | awk -F/ 'NR==1 { print "."; next }
                 { indent=""; for (i=2; i<NF; i++) indent=indent "│   "; print indent "├── " $NF }'
  fi
  echo '```'
  echo
  echo "## Where things live"
  echo
  echo "| Path | Purpose |"
  echo "|---|---|"
  echo "| \`PLAN.md\` | week-by-week plan; source of truth for what's next |"
  echo "| \`CLAUDE.md\` | context + rules for AI assistants |"
  echo "| \`docs/ARCHITECTURE.md\` | 8 modules, interfaces, state machine, test plan |"
  echo "| \`docs/decisions/\` | ADRs — read before changing a decided approach |"
  echo "| \`docs/PROGRESS.md\` | weekly log (shipped / AI-assisted / blocked / next) |"
  echo "| \`docs/proposal/\` | proposal + design doc LaTeX sources |"
  echo "| \`app/\` | Spring Boot application (from week 1) |"
  echo "| \`app/src/main/java/in/ac/iitm/cs5013/cyclebooking/<module>/\` | one package per module |"
  echo "| \`app/src/test/java/...\` | tests, mirroring main; ≥1 per module |"
  echo "| \`scripts/\` | repo-map.sh, weekly-update.sh |"
} > "$OUT"

echo "wrote $OUT"
